### PR TITLE
Actually filter status triggers

### PR DESCRIPTION
**Pull request by omgjlk**
The existing code did not filter on the status being set on the event
itself, it was only looking at (all) the statuses that exist on the change.
This led to false triggers, where an entity was setting an unrelated
status, but the pipeline would trigger because a required status (which
was the trigger status) was already set.

A new test case has been added to cover this scenario.

I also noticed that the calls to fake_github.emitEvent were wrong. The
argument being passed in (presumably for status) was actually setting
the context.

Fixes BonnyCI/projman#124

Change-Id: I694ecc72d962b8cc035ce408bb6e5628b5fdbc49

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/check_github/BonnyCI/zuul/43/1492131956.74/bonnyci-run-check : FAILURE in 18m 13s

**Review by ConsoleCatzirl — COMMENTED** [review]
:ok: LGTM, but will let others review as well

**Review by gandelman-a — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/gate_github/BonnyCI/zuul/43/1492192389.01/bonnyci-run-gate : FAILURE in 1h 18m 07s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.org/gate_github/BonnyCI/zuul/43/1492197081.48/bonnyci-run-gate : FAILURE in 41s

**Comment by anne-bonny** [comment]
Merge Failed! Help can be found at https://bonnyci.org/lore/end_users/use/#handling-merge-failures

**Pull request merged**
