### PR TITLE
Use integration_id with github

### PR DESCRIPTION
**Pull request by jamielennox**
The basics of authenticating to github as an integration when posting
comments and cloning. This is still a WIP.

### CODE REVIEW

**Comment by jamielennox** [comment]
Squashed these two and submitted for review at: https://review.openstack.org/411544

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- telnet://192.168.2.66:19885 : FAILURE in 7s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- telnet://192.168.2.70:19885 : FAILURE in 15m 50s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- https://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483503726.12/tox_py27 : FAILURE in 14m 59s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- telnet://192.168.2.72:19885 : FAILURE in 17m 32s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483508138.21/tox_py27 : FAILURE in 15m 02s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483551743.3/tox_py27 : FAILURE in 16m 01s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483555167.03/tox_py27 : FAILURE in 15m 59s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483559540.85/tox_py27 : FAILURE in 16m 48s

**Comment by rattboi** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483564351.44/tox_py27 : FAILURE in 18m 14s

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483568092.34/tox_py27 : FAILURE in 17m 12s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483571853.62/tox_py27 : FAILURE in 19m 01s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483575077.27/tox_py27 : FAILURE in 18m 44s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/5/1483576553.03/tox_py27 : FAILURE in 16m 20s

**Comment by jamielennox** [comment]
recheck

**Review by omgjlk — APPROVED** [review]

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Starting gate_github jobs.

**Pull request merged**
